#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     libbin2txt
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

const
  _libcrash =
  require(
    "crash-js");
const
  _dirname =
    _libcrash._dirname;
const
  _error_display =
    _libcrash._error_display;
const
  _ext_rm =
    _libcrash._ext_rm;
const
  _file_exists =
    _libcrash._file_exists;
const
  _file_read =
    _libcrash._file_read;
const
  _file_write =
    _libcrash._file_write;
const
  _fs_worker_start =
    _libcrash._fs_worker_start;
const
  _json_read =
    _libcrash._json_read;
const
  _ls =
    _libcrash._ls;
const
  _mkdir =
    _libcrash._mkdir;
const
  _msg_info =
    _libcrash._msg_info;
const
  _msg_error =
    _libcrash._msg_error;
const
  _stat =
    _libcrash._stat;
const
  _tmcsplit =
  require(
    "tmcsplit");
const
  _split =
    _tmcsplit._split;

async function
  _buffer_prepare(
    _in,
    _out,
    _buffer_size_bytes) {
  let
    _in_size_bytes,
    _size_max,
    _split_opts,
    _msg;
  _size_max =
    0;
  _in_size_bytes =
    _stat(
      _in).size;
  _msg =
    `File '${_in}' has size ` +
    `'${_in_size_bytes}' bytes.`;
  _msg_info(
    _msg);
  console.log(
    typeof(
      _in_size_bytes));
  _blocks_total =
    Math.ceil(
      _in_size_bytes /
      _buffer_size_bytes);
  _msg =
    `Splitting file '${_in}' in ` +
    `'${_blocks_total}' blocks of ` +
    `'${_in_size_bytes}' bytes.`;
  _msg_info(
    _msg);
  _split_opts = [
    _in,
    `${_out}.block.`,
    _blocks_total,
    _size_max
  ];
  _output_files =
    await _split.apply(
      null,
      _split_opts);
  return _output_files;
}

async function
  _input_data_check() {
  if ( ! _file_exists(
           _in) ) {
    const
      _msg =
        `File '${_in}' does ` +
        'not exist.';
    _msg_error(
      _msg,
      1);
  }
}

async function
  _bin2txt(
    _in,
    _out,
    _format,
    _length,
    _buffer_size_bytes,
    _amount_only) {
  let
    _block,
    _blocks_total,
    _chunks_total,
    _chunk_current,
    _block_current,
    _block_last,
    _dir,
    _file,
    _msg,
    _worker;
  // const
  //   _dir =
  //     "/test_dir";
  // const
  //   _file =
  //     `${_dir}/test_file`;
  // const
  //   _content =
  //     `${_in} ${_out}`;
  if ( typeof window !== 'undefined' ) {
    await _fs_worker_start(
        "fs-worker.js");
  }
  _input_data_check();
  const
    _blocks =
      _buffer_prepare(
        _in,
        _out,
        _buffer_size_bytes);
  _chunks_total =
    0;
  _chunk_current =
    0;
  _block_current =
    1;
  for ( _block of _blocks) {
    _msg =
      `Reading block '${_block}' ` +
      `('${_block_current}'` +
      `of '${_blocks_total}').`;
    _msg_info(
      _msg);
    if ( _block_current < _blocks_total ) {
      _block_last =
        false;
    }
    else if ( _block_current == _blocks_total ) {
      _block_last =
        "true";
      if ( _format === "base64" ) {
        _base64_encode(
          _block,
          _length,
          _block_last);
      _block_current =
        _block_current + 1;
    }
  }
  for ( _block of _blocks ) {
    _rm(
      _block);
  }
  if ( _amount_only === true ) {
    console.log(
      _chunks_total);
  }
  elif [[ "${_amount_only}" == "n" ]]; then
    _msg=(
      "Finished '${_format}' encoding"
      "input file '${_in}'."
    )
    _msg_info \
      "${_msg[*]}"
  fi

  // console.log(
  //   _split
  // );
  // _msg =
  //   `Creating directory '${_dir}':`;
  // _msg_info(
  //   _msg);
  // _mkdir(
  //   _dir);
  // _msg =
  //   `Writing content '${_content}' to file '${_file}':`;
  // _msg_info(
  //   _msg);
  // _file_write(
  //   _file,
  //   _content);
  // _msg =
  //   `Content of directory '/':`;
  // _msg_info(
  //   _msg);
  // _dir_content =
  //   _ls(
  //     "/").unwrap();
  // console.log(
  //   _dir_content);
  // _msg =
  //   `Content of directory '${_dir}':`;
  // _msg_info(
  //   _msg);
  // _dir_content =
  //   _ls(
  //     _dir).unwrap();
  // console.log(
  //   _dir_content);
}

module.exports = {
  _bin2txt:
    _bin2txt,
};
