#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     libbin2txt
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

const
  _libcrash =
  require(
    "crash-js");
const
  _dirname =
    _libcrash._dirname;
const
  _error_display =
    _libcrash._error_display;
const
  _ext_rm =
    _libcrash._ext_rm;
const
  _file_exists =
    _libcrash._file_exists;
const
  _file_read =
    _libcrash._file_read;
const
  _file_write =
    _libcrash._file_write;
const
  _fs_worker_start =
    _libcrash._fs_worker_start;
const
  _json_read =
    _libcrash._json_read;
const
  _ls =
    _libcrash._ls;
const
  _mkdir =
    _libcrash._mkdir;
const
  _msg_info =
    _libcrash._msg_info;
const
  _msg_error =
    _libcrash._msg_error;
const
  _rm =
    _libcrash._rm;
const
  _seq =
    _libcrash._seq;
const
  _stat =
    _libcrash._stat;
const
  _tmcsplit =
  require(
    "tmcsplit");
const
  _split =
    _tmcsplit._split;

async function
  _buffer_prepare(
    _in,
    _out,
    _buffer_size_bytes) {
  let
    _in_size_bytes,
    _size_max,
    _split_opts,
    _msg;
  _size_max =
    0;
  _in_size_bytes =
    _stat(
      _in).size;
  _msg =
    `File '${_in}' has size ` +
    `'${_in_size_bytes}' bytes.`;
  _msg_info(
    _msg);
  const
    _blocks_total =
      Math.ceil(
        _in_size_bytes /
        _buffer_size_bytes);
  _msg =
    `Splitting file '${_in}' in ` +
    `'${_blocks_total}' blocks of ` +
    `'${_in_size_bytes}' bytes.`;
  _msg_info(
    _msg);
  _split_opts = [
    _in,
    `${_out}.block.`,
    _blocks_total,
    _size_max
  ];
  _output_files =
    await _split.apply(
      null,
      _split_opts);
  return _output_files;
}

function
  _base64_block_encode(
    _file) {
  let
    _buffer,
    _content,
    _string;
  _content =
    _cat(
      _file);
  if ( typeof window === 'undefined' &&
       ( typeof global !== 'undefined' &&
         global.global === global ) &&
       typeof __webpack_require__ !== 'function' ) {
    _buffer =
      Buffer.from(
        _content);
    _string =
      _buffer.toString(
        "base64");
  }
  else {
    _string =
      btoa(string);
  }
  return _string;
}

async function
  _chunk_split(
    _in,
    _length,
    _prefix,
    _block_last) {
  let
    _chunk,
    _chunks,
    _content,
    _cut,
    _head,
    _msg,
    _out,
    _total;
  _total =
    _in.length;
  _chunks =
    Math.ceil(
      _chunk_current +
      _total /
        _length);
  if ( _chunks < 2 ) {
    _out =
      _prefix;
    _file_write(
      _out,
      _in);
    return 0;
  }
  _msg =
    `Chunking '${_total}' ` +
    `letters into '${_chunks}'.`;
  _msg_info(
    _msg);
  for ( _chunk of _seq(
                    _chunk_current + 1,
                    _chunks) ) {
    _chunk_start =
      ( ( _chunk -
          _chunk_current ) *
        _length ) -
      _length;
    _cut =
      _in.substring(
        _chunk_start,
        _chunk_start + _length);
    _out =
      `${_prefix}.${_chunk}`;
    _msg =
      `Writing chunk ${_chunk} in file '${_out}' ` +
      `of length ${_cut.length} out of ${_chunks}.`;
    _msg_info(
      _msg);
    if ( _chunk < _chunks ) {
      printf(
        _out,
        _cut);
    }
    else if ( _chunk == _chunks ) {
      if ( _block_last == "true" ) {
        _file_write(
          _out,
          _cut);
      }
      else if ( _block_last == "false" ) {
        _msg =
          "Last chunk of non-last block, " +
          "adding a newline character at the end (nope).";
        _msg_info(
          _msg);
        _file_write(
          _out,
          _cut);
      }
    }
  }
  _chunk_current =
    _chunks;
  _msg=
    "Finished encoding block.";
  _msg_info(
    _msg);
}

async function
  _base64_encode(
    _block,
    _length,
    _block_last) {
  let
    _txt,
    _msg;
  _txt =
    _base64_block_encode(
      _block);
  _msg =
    `Block '${_block}' encoded ` +
    `length: ${_txt.length}.`;
  _msg_info(
    _msg);
  if ( _amount_only === "false" ) {
    _chunk_split(
      _txt,
      _length,
      _out,
      _block_last);
  }
  else if ( _amount_only === "true" ) {
    _chunks_total =
      Math.ceil(
        _chunks_total +
        _txt.length /
          _length);
  }
  else {
    _msg =
      `Value of the 'amount_only' can ` +
      `be true or false. Current: '${_amount_only}'.`;
    _msg_error(
      _msg,
      1);
  }
  _msg =
    "Finished encoding block " +
    `'${_block}'.`;
  _msg_info(
    _msg);
}

async function
  _input_data_check(
    _in) {
  if ( ! _file_exists(
           _in) ) {
    const
      _msg =
        `File '${_in}' does ` +
        'not exist.';
    _msg_error(
      _msg,
      1);
  }
}

async function
  _bin2txt(
    _in,
    _out,
    _format,
    _length,
    _buffer_size_bytes,
    _amount_only) {
  let
    _block,
    _blocks_total,
    _chunks_total,
    _chunk_current,
    _block_current,
    _block_last,
    _msg,
    _rm_args,
    _worker;
  if ( typeof window !== 'undefined' ) {
    await _fs_worker_start(
        "fs-worker.js");
  }
  _input_data_check(
    _in);
  const
    _blocks =
      await _buffer_prepare(
        _in,
        _out,
        _buffer_size_bytes);
  console.log(
    _blocks);
  _blocks_total =
    _blocks.length;
  _chunks_total =
    0;
  _chunk_current =
    0;
  _block_current =
    1;
  for ( _block of _blocks ) {
    _msg =
      `Reading block '${_block}' ` +
      `('${_block_current}' ` +
      `of '${_blocks_total}').`;
    _msg_info(
      _msg);
    if ( _block_current < _blocks_total ) {
      _block_last =
        "false";
    }
    else if ( _block_current == _blocks_total ) {
      _block_last =
        "true";
      if ( _format === "base64" ) {
        _base64_encode(
          _block,
          _length,
          _block_last);
      _block_current =
        _block_current + 1;
      }
      else {
        _msg =
          "Unknown encoding format " +
          `${_format}.`;
        _msg_error(
          _msg,
          1);
      }
    }
  }
  for ( _block of _blocks ) {
    _rm_args = [
      _block
    ];
    _rm(
      _rm_args);
  }
  if ( _amount_only === "true" ) {
    console.log(
      _chunks_total);
  }
  else if ( _amount_only === "false" ) {
    _msg =
      `Finished '${_format}' encoding ` +
      `input file '${_in}'.`;
    _msg_info(
      _msg);
  }
}

module.exports = {
  _bin2txt:
    _bin2txt,
};
