#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     libtxt2bin
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

const
  _libcrash =
  require(
    'crash-js');
const
  _ext_rm =
    _libcrash._ext_rm;
const
  _file_read =
    _libcrash._file_read;
const
  _file_write =
    _libcrash._file_write;
const
  _fs_worker_start =
    _libcrash._fs_worker_start;
const
  _json_read =
    _libcrash._json_read;
const
  _ls =
    _libcrash._ls;
const
  _mkdir =
    _libcrash._mkdir;
const
  _msg_info =
    _libcrash._msg_info;
const
  _msg_error =
    _libcrash._msg_error;

async function
  _assemble(
    _input_files,
    _output_path,
    _argument_type) {
  let
    _data,
    _dir,
    _file,
    _msg,
    _worker;
  if ( _argument_type == "list" ) {
    const
      _list =
        _input_files[
          0];
    _msg =
      `Merging files from list at ` +
      `'${_list}' into '${_output_file}'.`
  }
  else if ( _argument_type == "file" ) {
    _msg =
      `Merging '${_input_files}' into ` +
      `'${_output_file}'.`;
  }
  _msg_info(
    _msg);
  const
    _fs_worker_started =
      await _fs_worker_start(
          "fs-worker.js");
  for ( _file of _input_files ) {
    _data =
      _file_read(
        _file);
    _file_append(
      _data,
      _out);
  }
  _msg =
    `Merging finished.`;
  _msg_info(
    _msg);
}

function
  _base64_decode(
    _output_file,
    _input_files) {
  let
    _data,
    _msg,
    _txt;
  if ( typeof(
         _input_files) == "undefined" ||
       _input_files == [] ||
       _input_files == "" ) {
    _msg =
      "No input files given in input.";
    _msg_error(
      _msg,
      1);
  }
  _txt =
    _input_files[
      0];
  if ( 0 < _input_files.length ) {
    _txt =
      "";
  }
  true
}

function
  _txt2bin(
    _output_file,
    _encoding_format,
    _argument_type,
    _input_files) {
  let
    _list;
  if ( _argument_type == "list" ) {
    const
      _list =
        _input_files[
          0];
    _input_files =
      _cat(
        _list).split(
          "\n");
  }
  if ( _encoding_format == "base64" ) {
    _base64_decode(
      _output_file,
      _input_files);
  }
}

module.exports = {
  _txt2bin:
    _txt2bin
}
