#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     libtxt2bin
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */

const
  _base64_stream_module =
    require(
      "base64-stream");
const
  _fs_module =
    require(
      "fs");
const
  _write_stream_create =
    _fs_module.createWriteStream;
const
  _read_stream_create =
    _fs_module.createReadStream;
const
  _stat =
    _fs_module.stat;
const
  _promise =
    require(
      "bluebird");
/* global
     _promise_reject */
const
  _promise_reject =
    _promise.reject;
/* global
     _promise_resolve */
const
  _promise_resolve =
    _promise.resolve;
const
  _promisify =
    _promise.promisify;
/* global
     _map_series */
const
  _map_series =
    _promise.mapSeries;
const
  _libcrash =
    require(
      'crash-js');
/* global
     _cat */
const
  _cat =
    _libcrash._cat;
/* global
     _ext_rm */
const
  _ext_rm =
    _libcrash._ext_rm;
/* global
     _file_append */
const
  _file_append =
    _libcrash._file_append;
/* global
     _file_exists */
const
  _file_exists =
    _libcrash._file_exists;
/* global
     _file_read */
const
  _file_read =
    _libcrash._file_read;
/* global
     _fs_worker_start */
const
  _fs_worker_start =
    _libcrash._fs_worker_start;
/* global
     _json_read */
const
  _json_read =
    _libcrash._json_read;
/* global
     _ls */
const
  _ls =
    _libcrash._ls;
/* global
     _mkdir */
const
  _mkdir =
    _libcrash._mkdir;
/* global
     _mktemp */
const
  _mktemp =
    _libcrash._mktemp;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _path_join */
const
  _path_join =
    _libcrash._path_join;

async function
  _assemble(
    _input_files,
    _output_file,
    _argument_type) {
  let
    _data,
    _dir,
    _file,
    _msg,
    _worker;
  if ( _argument_type == "list" ) {
    const
      _list =
        _input_files[
          0];
    _msg =
      `Merging files from list at ` +
      `'${_list}' into '${_output_file}'.`;
  }
  else if ( _argument_type == "file" ) {
    _msg =
      `Merging '${_input_files}' into ` +
      `'${_output_file}'.`;
  }
  _msg_info(
    _msg);
  const
    _fs_worker_started =
      await _fs_worker_start(
          "fs-worker.js");
  for ( _file of _input_files ) {
    _data =
      _file_read(
        _file);
    _file_append(
      _data,
      _output_file);
  }
  _msg =
    `Merging finished.`;
  _msg_info(
    _msg);
}

async function
  _base64_decode(
    _output_file,
    _input_files,
    _argument_type) {
  let
    _data,
    _msg,
    _txt;
  if ( typeof(
         _input_files) == "undefined" ||
       _input_files == [] ||
       _input_files == "" ) {
    _msg =
      "No input files given in input.";
    _msg_error(
      _msg,
      1);
  }
  _txt =
    _input_files[
      0];
  if ( 0 < _input_files.length ) {
    const
      _tmp_dir =
        await _mktemp();
    console.log(
      _tmp_dir);
    _txt =
      _path_join( [
        _tmp_dir,
        "merge.base64" ]);
    _assemble(
      _txt,
      _input_files,
      _argument_type);
  }
  _msg =
    `Decoding '${_txt}' into '${_output_file}'`;
  _msg_info(
    _msg);
  console.log(
    _base64_stream_module);
  console.log(
    _base64_stream_module.Base64Encode);
}

function
  _input_texts_check(
    _input_texts) {
  let
    _file,
    _input_file_exists;
  for ( _file of _input_texts ) {
    _input_file_exists =
      _file_exists(
        _file);
    if ( ! _input_file_exists ) {
      const
        _msg =
          `Input file '${_file}' does not ` +
          `exist.`;
        _msg_error(
          _msg,
          1);
    }
  }
}

async function
  _txt2bin(
    _output_file,
    _encoding_format,
    _argument_type,
    _input_files,
    _input_files_sanity_check) {
  const
    _input_files_sanity_check_type =
      typeof(
        _input_files_sanity_check);
  if ( _input_files_sanity_check_type == "undefined" ||
         _input_files_sanity_check == "" ||
         _input_files_sanity_check == "true" ) {
    _input_files_sanity_check =
      true;
  }
  if ( _input_files_sanity_check == "false" ) {
    _input_files_sanity_check =
      false;
  }
  if ( _argument_type == "list" ) {
    const
      _list =
        _input_files[
          0];
    _input_files =
      _cat(
        _list).split(
          "\n");
  }
  if ( _input_files_sanity_check ) {
    _input_texts_check(
      _input_files);
  }
  if ( _encoding_format == "base64" ) {
    await _base64_decode(
      _output_file,
      _input_files,
      _argument_type);
  }
}

module.exports = {
  _input_texts_check:
    _input_texts_check,
  _txt2bin:
    _txt2bin
};
