#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     txt2bin
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

// Crash Javascript global variables

/* global
     quiet */

const
  _libcrash =
  require(
    'crash-js');
/* global
     _argv_get */
const
  _argv_get =
    _libcrash._argv_get;
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _error_display */
const
  _error_display =
    _libcrash._error_display;
/* global
     _ext_rm */
const
  _ext_rm =
    _libcrash._ext_rm;
/* global
     _ext_rm */
const
  _file_read =
    _libcrash._file_read;
/* global
     _file_write */
const
_file_write =
  _libcrash._file_write;
/* global
     _fs_worker_start */
const
  _fs_worker_start =
    _libcrash._fs_worker_start;
/* global
     _json_read */
const
  _json_read =
    _libcrash._json_read;
/* global
     _ls */
const
  _ls =
    _libcrash._ls;
/* global
     _mkdir */
const
  _mkdir =
    _libcrash._mkdir;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error;

function
  _global_variables() {
  /* global
       app_name */
  app_name =
    "txt2bin";
  /* global
       make_date */
  make_date =
    "";
  /* global
       out_file */
  out_file =
    "";
  /* global
       encoding_format */
  encoding_format =
    "";
  /* global
       argument_type */
  argument_type =
    "";
  in_texts =
    [];
  quiet =
    "";
}

async function
  _txt2bin(
    _target_message,
    _target_planet) {
  let
    _agent,
    _dir_content,
    _content,
    _dir,
    _file,
    _msg,
    _worker;
  _dir =
    "/test_dir";
  _file =
    `${_dir}/test_file`;
  _content =
    `${_target_message} ${_target_planet}`;
  await _fs_worker_start(
      "fs-worker.js");
  _msg =
    `Creating directory '${_dir}':`;
  _msg_info(
    _msg);
  _mkdir(
    _dir);
  _msg =
    `Writing content '${_content}' to file '${_file}':`;
  _msg_info(
    _msg);
  _file_write(
    _file,
    _content);
  _msg =
    `Content of directory '/':`;
  _msg_info(
    _msg);
  _dir_content =
    _ls(
      "/").unwrap();
  console.log(
    _dir_content);
  _msg =
    `Content of directory '${_dir}':`;
  _msg_info(
    _msg);
  _dir_content =
    _ls(
      _dir).unwrap();
  console.log(
    _dir_content);
}

function
  _config_show() {
  let
    _line,
    _text;
  _text = [
    `      Runtime environment: ${runtime_environment}`,
    `           Target message: ${target_message}`,
    `            Target planet: ${target_planet}`,
  ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}


function
  _usage(
    _exit_code) {
  let
    _line,
    _text;
  _text = [
    "Hello world application for browsers and computers",
    "",
    "Usage:",
    "  ahsi",
    "    <quiet>",
    "    <message>",
    "    <planet>",
    "",
    "Args:",
    "  <quiet>                          Can be 'y' or 'n'",
    "                                   Default: y",
  ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
  process.exit(
    _exit_code);
}

function 
  _cmdline_parse() {
  let
    _argv,
    _help_display,
    _msg;
  const
    _argv_args = {
      "booleans": [
        "h",
        "help",
        "v",
        "verbose"
      ]
    };
  _argv =
    _argv_get(
       _argv_args);
  _options =
    _argv[
      "_"];
  quiet = 
    "y";
  _help_display =
    false;
  if ( "h" in _argv ) {
    _help_display =
      true;
  }
  if ( "help" in _argv ) {
    _help_display =
      true;
  }
  runtime_environment =
    "node";
  if ( _options.indexOf(
         "--help") > -1 ||
       _options.indexOf(
         "-h") > -1) {
    _help_display =
      true;
  }
  if ( _help_display ) {
    quiet =
      "n";
    _overrides_set();
    _usage(
      0);
  }
  if ( typeof(
         _argv) == "undefined" ||
       _argv[
         "_"].length < 1 ) {
    _msg =
      "Input file argument required.";
    _msg_error(
      _msg,
      0);
    _usage(
      1);
  }
  in_file =
    _argv[
      "_"][
        0];
  if ( _argv[
         "_"].length < 2 ) {
    out_txt_prefix =
      in_file +
      ".base64";
  }
  if ( "L" in _argv ) {
    string_length =
      _argv[
        "L"];
  }
  if ( "string-length" in _argv ) {
    string_length =
      _argv[
        "string-length"];
  }
  if ( "s" in _argv ) {
    amount_only =
      _argv[
        "s"];
  }
  if ( "amount-only" in _argv ) {
    amount_only =
      _argv[
        "amount-only"];
  }
  if ( "v" in _argv ) {
    verbose =
      true;
  }
  if ( "verbose" in _argv ) {
    verbose =
      true;
  }
  if ( verbose ) {
    quiet =
      "n";
  }
}

function
  _url_parse() {
  let
    _argv;
  runtime_environment =
    "browser";
  _argv =
    _argv_url_get();
  target_message =
    _argv_url_get(
      "target_message")[0];
  target_planet =
    _argv_url_get(
      "target_planet")[0];
  quiet =
    _argv_url_get(
      "quiet");
  if ( quiet.length === 0 ) {
    quiet =
      "n";
  }
}

_global_variables();

_global_variables();
if ( _cmdline_check(
       "txt2bin") == true ) {
  _cmdline_parse();
}
else {
  _url_parse();
}
_config_show();
app_opts = [
  out_file,
  encoding_format,
  argument_type,
  in_texts
];
_txt2bin.apply(
  null,
  app_opts);
