#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     txt2bin
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

// Crash Javascript global variables

/* global
     quiet:
       writable */
/* global
     runtime_environment:
       writable */

const
  _libcrash =
  require(
    'crash-js');
/* global
     _argv_get */
const
  _argv_get =
    _libcrash._argv_get;
/* global
     _argv_url_get */
const
  _argv_url_get =
    _libcrash._argv_url_get;
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _error_display */
const
  _error_display =
    _libcrash._error_display;
/* global
     _ext_rm */
const
  _ext_rm =
    _libcrash._ext_rm;
/* global
     _file_read */
const
  _file_read =
    _libcrash._file_read;
/* global
     _file_write */
const
_file_write =
  _libcrash._file_write;
/* global
     _fs_worker_start */
const
  _fs_worker_start =
    _libcrash._fs_worker_start;
/* global
     _json_read */
const
  _json_read =
    _libcrash._json_read;
/* global
     _ls */
const
  _ls =
    _libcrash._ls;
/* global
     _mkdir */
const
  _mkdir =
    _libcrash._mkdir;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _process_exit */
const
  _process_exit =
    _libcrash._process_exit;
const
  _encoding_tools =
    require(
      "./encoding-tools");
/* global
     _txt2bin */
const
  _txt2bin =
    _encoding_tools._txt2bin;

function
  _global_variables() {
  /* global
       app_name:
         writable */
  app_name =
    "txt2bin";
  /* global
       app_opts:
         writable */
  app_opts =
    [];
  /* global
       make_date:
         writable */
  make_date =
    "";
  /* global
       output_file:
         writable */
  output_file =
    "";
  /* global
       encoding_format:
         writable */
  encoding_format =
    "";
  /* global
       argument_type:
         writable */
  argument_type =
    "";
  /* global
       input_texts:
         writable */
  input_texts =
    [];
  /* global
       quiet:
         writable */
  quiet =
    "";
  /* global
       verbose:
         writable */
  verbose =
    "";
}

function
  _config_show() {
  let
    _line;
  const
    _text = [
      `                Call date: ${call_date}`,
      `      Runtime environment: ${runtime_environment}`,
      `            Argument type: ${argument_type}`,
      `          Encoding format: ${encoding_format}`,
      `              Output file: ${output_file}`,
      `       Input text file(s): ${input_texts}`,
    ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line;
  const
    _text = [
      "",
      "Converts text to binary.",
      "",
      "Usage:",
      `  ${app_name}`,
      `    [options]`,
      `    <out-file>`,
      `    [in-text]`,
      "",
      "  options:",
      "     -t, --argument-type    Possible values are 'file' and",
      "       <type>               'list'.",
      "                            When it is 'file' the arguments",
      "                            are the encoded file paths,",
      "                            when it is 'list' the argument is",
      "                            a file containing the paths of the",
      "                            encoded files.",
      `                            Default: '${argument_type}`,
      "     -f --encoding-format   Encoding format ('base64').",
      `       <format>             Default: '${encoding_format}'`,
      "",
      "     -h                     This message.",
      "     -v                     Enable verbose output",
      ""
    ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
  _process_exit(
    _exit_code);
}

function 
  _overrides_set() {
  if ( make_date == "" ) {
    make_date =
      _get_date_human();
  }
  if ( encoding_format == "" ||
       typeof(
         encoding_format) == "undefined" ) {
    encoding_format =
      "base64";
  }
  if ( string_length == "" ||
       typeof(
         string_length) == "undefined" ) {
    string_length =
      "10000";
  }
  if ( buffer_size == "" ||
       typeof(
         buffer_size) == "undefined" ) {
    buffer_size =
      "2000000"; // 2MB
  }
  if ( amount_only == "" ||
         typeof(
           amount_only) == "undefined" ) {
    amount_only =
      "false";
  }
}

function 
  _cmdline_parse() {
  let
    _help_display,
    _msg;
  const
    _argv_args = {
      "booleans": [
        "h",
        "help",
        "v",
        "verbose"
      ]
    };
  const
    _argv =
      _argv_get(
         _argv_args);
  const
    _options =
      _argv[
        "_"];
  quiet = 
    "y";
  _help_display =
    false;
  if ( "h" in _argv ) {
    _help_display =
      true;
  }
  if ( "help" in _argv ) {
    _help_display =
      true;
  }
  runtime_environment =
    "node";
  if ( _options.indexOf(
         "--help") > -1 ||
       _options.indexOf(
         "-h") > -1) {
    _help_display =
      true;
  }
  if ( _help_display ) {
    quiet =
      "n";
    _overrides_set();
    _usage(
      0);
  }
  if ( typeof(
         _argv) == "undefined" ||
       _argv[
         "_"].length < 1 ) {
    _msg =
      "Input file argument required.";
    _msg_error(
      _msg,
      0);
    _usage(
      1);
  }
  out_file =
    _argv[
      "_"][
        0];
  input_texts =
    _argv[
      "_"].slice(
        1);
  if ( "t" in _argv ) {
    argument_type =
      _argv[
        "t"];
  }
  if ( "argument-type" in _argv ) {
    argument_type =
      _argv[
        "argument-type"];
  }
  if ( "f" in _argv ) {
    encoding_format =
      _argv[
        "f"];
  }
  if ( "encoding-format" in _argv ) {
    encoding_format =
      _argv[
        "encoding-format"];
  }
  if ( "v" in _argv ) {
    verbose =
      true;
  }
  if ( "verbose" in _argv ) {
    verbose =
      true;
  }
  if ( verbose ) {
    quiet =
      "n";
  }
}

function
  _url_parse() {
  runtime_environment =
    "browser";
  encoding_format =
    _argv_url_get(
      "encoding_format")[
        0];
  argument_type =
    _argv_url_get(
      "argument_type")[
        0];
  output_file =
    _argv_url_get(
      "output_file")[
        0];
  input_texts =
    _argv_url_get(
      "input_texts");
  quiet =
    _argv_url_get(
      "quiet");
  if ( quiet.length === 0 ) {
    quiet =
      "n";
  }
}

_global_variables();

_global_variables();
if ( _cmdline_check(
       "txt2bin") ||
     _cmdline_check(
       "txt2bin.js") ) {
  _cmdline_parse();
}
else {
  _url_parse();
}
_config_show();
app_opts = [
  output_file,
  encoding_format,
  argument_type,
  input_texts
];
_txt2bin.apply(
  null,
  app_opts);
